# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupremeCourtJustices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('law_school', models.CharField(max_length=50)),
                ('speech', models.URLField()),
                ('hobby', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('birth_date', models.DateField()),
                ('appointed_by', models.CharField(max_length=20)),
            ],
        ),
    ]
