# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotus_app', '0002_auto_20160613_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremecourtjustice',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
